baseURL: https://masputrawae.github.io/kode-ngasal-ngoding-syariah
languageCode: id
title: MasPutraWae
enableEmoji: true

markup:
  tableOfContents:
    endLevel: 6
    ordered: true
    startLevel: 2
  
  highlight:
    codeFences: true
    guessSyntax: true
    style: 'github-dark'
    noClasses: false
    lineNumbersInTable: false
    lineNos: false
    anchorLineNos: false
    lineAnchors: ''
    lineNoStart: 1
    tabWidth: 4

  goldmark:
    renderHooks:
      image:
        enableDefault: true
        useEmbedded: auto
      link:
        enableDefault: true
        useEmbedded: auto
    renderer:
      unsafe: true
    extensions:
      definitionList: true
      extras:
        delete:
          enable: true
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
      footnote: true
    parser:
      wrapStandAloneImageWithinParagraph: true
      attribute:
        block: true
        title: true

module:
  hugoVersion:
    extended: true
    min: '0.146.0'

  mounts:
    - source: 'content'
      target: 'content'
      excludeFiles: '99_templates/*'
    - source: 'content'
      target: 'content'
      excludeFiles: '.obsidian/*'
    - source: 'content'
      target: 'content'
      excludeFiles: '.trash/*'
    - source: 'content'
      target: 'content'
      excludeFiles: 'private/*'
