baseURL: https://masputrawae.github.io
languageCode: id
title: MasPutraWae
enableEmoji: true

markup:
  tableOfContents:
    endLevel: 6
    ordered: false
    startLevel: 2
  
  highlight:
    codeFences: true
    guessSyntax: true
    style: 'github-dark'
    noClasses: false
    lineNumbersInTable: false
    lineNos: false
    anchorLineNos: false
    lineAnchors: ''
    lineNoStart: 1
    tabWidth: 4

  goldmark:
    renderer:
      unsafe: true
    parser:
      wrapStandAloneImageWithinParagraph: false
      attribute:
        block: true
        title: true

module:
  hugoVersion:
    extended: true
    min: '0.146.0'

  mounts:
    - source: 'content'
      target: 'content'
      excludeFiles: '99_templates/*'
    - source: 'content'
      target: 'content'
      excludeFiles: '.obsidian/*'
    - source: 'content'
      target: 'content'
      excludeFiles: '.trash/*'
    - source: 'content'
      target: 'content'
      excludeFiles: 'private/*'
