author: Putra Jaya
tagline:
  - Manusia Biasa
  - Semangat Belajar!
  - Semangat Koding!
logo: logo.webp
image: default-image.webp
description: Dolore nostrud voluptate ullamco et do exercitation est fugiat adipisicing mollit enim non. Qui reprehenderit est tempor cupidatat in fugiat deserunt.

favicons:
  - rel: icon
    type: image/x-icon
    href: assets/favicons/favicon.ico
  - rel: apple-touch-icon
    type: image/png
    size: 180x180
    href: assets/favicons/apple-touch-icon.png
  - rel: icon
    type: image/png
    size: 32x32
    href: assets/favicons/favicon-32x32.png
  - rel: icon
    type: image/png
    size: 16x16
    href: assets/favicons/favicon-16x16.png
  - rel: icon
    type: image/png
    size: 192x192
    href: assets/favicons/android-chrome-192x192.png
  - rel: icon
    type: image/png
    size: 512x512
    href: assets/favicons/android-chrome-512x512.png
  - rel: manifest
    href: manifest.json