# <===> DEFAULT PARAMS <===>
baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[params]
[params.author]
  name = 'Putra Jaya'
  tagline = 'Manusia Biasa'
  description = 'Magna cillum nisi dolore consequat.'
  

# <===> MENUS <===>
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[markup]
  # [markup.tableOfContents]
  #   endLevel    = 6
  #   ordered     = false
  #   startLevel  = 2

  [markup.highlight]
    codeFences          = true
    guessSyntax         = true
    style               = "github-dark"
    noClasses           = true
    lineNumbersInTable  = true
    lineNos             = true
    anchorLineNos       = true
    lineAnchors         = ''
    lineNoStart         = 1
    tabWidth            = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe    = true

    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      
      [markup.goldmark.parser.attribute]
        block = true
        title = true
        
[module]
  [module.hugoVersion]
    extended = true
    min = '0.146.0'

  [[module.mounts]]
    source = "content"
    target = "content"
    excludeFiles = "99_templates/*"
  [[module.mounts]]
    source = "content"
    target = "content"
    excludeFiles = ".obsidian/*"
  [[module.mounts]]
    source = "content"
    target = "content"
    excludeFiles = ".trash/*"
  [[module.mounts]]
    source = "content"
    target = "content"
    excludeFiles = "private/*"